Changed for loop for deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -95,40 +95,58 @@ jobs:
             echo "AWS_SECRET_ACCESS_KEY: $TARGET_AWS_SECRET_ACCESS_KEY"
             echo "AWS_SESSION_TOKEN: $TARGET_AWS_SESSION_TOKEN"
           }
-
-          # for file in iamConfigs/*.yaml; do
-          #   account_id=$(yq eval '.account_id' "$file")
-          #   role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
-          #   stack_name="IamRoleConfigStack-$account_id"
-          #   echo "Deploying stack $stack_name to account $account_id using role $role_arn"
-
           for file in iamConfigs/*.yaml; do
-            for account_id in $(yq eval '.account_id | .[]' "$file"); do
+            account_ids=$(yq eval '.account_id | .[]' "$file")
+            for account_id in $account_ids; do
               role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
               stack_name="IamRoleConfigStack-$account_id"
               echo "Deploying stack $stack_name to account $account_id using role $role_arn"
 
-            # Debug: Print the role ARN and account ID
-            echo "Role ARN: $role_arn"
-            echo "Account ID: $account_id"
+              # Assume the role for the current target account
+              assume_target_role $role_arn github-actions || continue
 
-            # Assume the role for the current target account
-            assume_target_role $role_arn github-actions
+              # Deploy the stack
+              AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN aws sts get-caller-identity
+              AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --require-approval never --context file=$file || { echo "Failed to deploy stack: $stack_name"; exit 1; }
 
-            # Deploy the stack
-            AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN aws sts get-caller-identity
-            AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --require-approval never --context file=$file || { echo "Failed to deploy stack: $stack_name"; exit 1; }
-
-
-            # Unset AWS credentials to clear them for the next iteration
-            unset TARGET_AWS_ACCESS_KEY_ID
-            unset TARGET_AWS_SECRET_ACCESS_KEY
-            unset TARGET_AWS_SESSION_TOKEN
-
-            # Debug: Confirm credentials are unset
-            echo "Unset AWS credentials"
+              # Unset AWS credentials
+              unset TARGET_AWS_ACCESS_KEY_ID TARGET_AWS_SECRET_ACCESS_KEY TARGET_AWS_SESSION_TOKEN
             done
           done
+
+          # # for file in iamConfigs/*.yaml; do
+          # #   account_id=$(yq eval '.account_id' "$file")
+          # #   role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
+          # #   stack_name="IamRoleConfigStack-$account_id"
+          # #   echo "Deploying stack $stack_name to account $account_id using role $role_arn"
+
+          # for file in iamConfigs/*.yaml; do
+          #   for account_id in $(yq eval '.account_id | .[]' "$file"); do
+          #     role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
+          #     stack_name="IamRoleConfigStack-$account_id"
+          #     echo "Deploying stack $stack_name to account $account_id using role $role_arn"
+
+          #   # Debug: Print the role ARN and account ID
+          #   echo "Role ARN: $role_arn"
+          #   echo "Account ID: $account_id"
+
+          #   # Assume the role for the current target account
+          #   assume_target_role $role_arn github-actions
+
+          #   # Deploy the stack
+          #   AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN aws sts get-caller-identity
+          #   AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --require-approval never --context file=$file || { echo "Failed to deploy stack: $stack_name"; exit 1; }
+
+
+          #   # Unset AWS credentials to clear them for the next iteration
+          #   unset TARGET_AWS_ACCESS_KEY_ID
+          #   unset TARGET_AWS_SECRET_ACCESS_KEY
+          #   unset TARGET_AWS_SESSION_TOKEN
+
+          #   # Debug: Confirm credentials are unset
+          #   echo "Unset AWS credentials"
+          #   done
+          # done
 
         env:
           IAM_ROLE_CONFIG_DIRECTORY: iamConfigs
