Changed Execution Role to GitHubActions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -63,12 +63,6 @@ jobs:
               echo -e "\n"
             done       
           
-      # - name: Configure AWS credentials with long term IAM user credentials
-      #   uses: aws-actions/configure-aws-credentials@v2
-      #   with:
-      #     aws-access-key-id: ${{ secrets.GITHUBACTIONS_ACCESS_KEY }}
-      #     aws-secret-access-key: ${{ secrets.GITHUBACTIONS_SECRETS_ACCESS_KEY }}
-      #     aws-region: us-east-1
 
       - name: Configure AWS Credentials using OIDC Identity
         uses: aws-actions/configure-aws-credentials@v4
@@ -115,7 +109,7 @@ jobs:
             export TARGET_AWS_SESSION_TOKEN=$(echo $credentials | jq -r '.Credentials.SessionToken')
 
             # Deploy the stack using the pre-synthesized template
-            AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --app "cdk.out" --require-approval never || { echo "Failed to deploy stack: $stack_name"; exit 1; }
+            AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --app "cdk.out" --require-approval never -r $role_arn || { echo "Failed to deploy stack: $stack_name"; exit 1; }
 
             # Unset AWS credentials
             unset TARGET_AWS_ACCESS_KEY_ID TARGET_AWS_SECRET_ACCESS_KEY TARGET_AWS_SESSION_TOKEN
@@ -125,109 +119,7 @@ jobs:
           fi
           done
 
-          # for file in iamConfigs/*.yaml; do
-          #   account_ids=$(yq eval '.account_id | .[]' "$file")
-          #   for account_id in $account_ids; do
-          #     role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
-          #     stack_name="IamRoleConfigStack-$account_id"
-          #     echo "Deploying stack $stack_name to account $account_id using role $role_arn"
-
-          #     # Assume the role for the current target account
-          #     credentials=$(aws sts assume-role --role-arn $role_arn --role-session-name github-actions || { echo "Failed to assume role: $role_arn"; exit 1; })
-          #     export TARGET_AWS_ACCESS_KEY_ID=$(echo $credentials | jq -r '.Credentials.AccessKeyId')
-          #     export TARGET_AWS_SECRET_ACCESS_KEY=$(echo $credentials | jq -r '.Credentials.SecretAccessKey')
-          #     export TARGET_AWS_SESSION_TOKEN=$(echo $credentials | jq -r '.Credentials.SessionToken')
-
-          #     # Deploy the stack using the pre-synthesized template
-          #     AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --app "cdk.out" --require-approval never --context file=$file || { echo "Failed to deploy stack: $stack_name"; exit 1; }
-
-          #     # Unset AWS credentials
-          #     unset TARGET_AWS_ACCESS_KEY_ID TARGET_AWS_SECRET_ACCESS_KEY TARGET_AWS_SESSION_TOKEN
-          #   done
-          # done
-
         env:
           IAM_ROLE_CONFIG_DIRECTORY: iamConfigs
           AWS_DEFAULT_REGION: us-east-1  # Set your default region if necessary
         
-      # - name: Deploy to Multiple Accounts
-      #   run: |
-      #     set -eo pipefail
-      #     source .venv/bin/activate
-
-      #     # Function to assume target account role
-      #     assume_target_role() {
-      #       local role_arn=$1
-      #       local session_name=$2
-
-
-      #     # Assume the target account role
-      #       credentials=$(aws sts assume-role --role-arn $role_arn --role-session-name $session_name || { echo "Failed to assume role: $role_arn"; exit 1; })
-      #       export TARGET_AWS_ACCESS_KEY_ID=$(echo $credentials | jq -r '.Credentials.AccessKeyId')
-      #       export TARGET_AWS_SECRET_ACCESS_KEY=$(echo $credentials | jq -r '.Credentials.SecretAccessKey')
-      #       export TARGET_AWS_SESSION_TOKEN=$(echo $credentials | jq -r '.Credentials.SessionToken')
-
-      #       # Debug: Print the assumed role credentials
-      #       echo "Assumed Role Credentials:"
-      #       echo "AWS_ACCESS_KEY_ID: $TARGET_AWS_ACCESS_KEY_ID"
-      #       echo "AWS_SECRET_ACCESS_KEY: $TARGET_AWS_SECRET_ACCESS_KEY"
-      #       echo "AWS_SESSION_TOKEN: $TARGET_AWS_SESSION_TOKEN"
-      #     }
-      #     for file in iamConfigs/*.yaml; do
-      #       account_ids=$(yq eval '.account_id | .[]' "$file")
-      #       for account_id in $account_ids; do
-      #         role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
-      #         stack_name="IamRoleConfigStack-$account_id"
-      #         echo "Deploying stack $stack_name to account $account_id using role $role_arn"
-
-      #         # Assume the role for the current target account
-      #         assume_target_role $role_arn github-actions || continue
-
-      #         # Deploy the stack
-      #         AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN aws sts get-caller-identity
-      #         AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --require-approval never --context file=$file || { echo "Failed to deploy stack: $stack_name"; exit 1; }
-
-      #         # Unset AWS credentials
-      #         unset TARGET_AWS_ACCESS_KEY_ID TARGET_AWS_SECRET_ACCESS_KEY TARGET_AWS_SESSION_TOKEN
-      #       done
-      #     done
-
-          # # for file in iamConfigs/*.yaml; do
-          # #   account_id=$(yq eval '.account_id' "$file")
-          # #   role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
-          # #   stack_name="IamRoleConfigStack-$account_id"
-          # #   echo "Deploying stack $stack_name to account $account_id using role $role_arn"
-
-          # for file in iamConfigs/*.yaml; do
-          #   for account_id in $(yq eval '.account_id | .[]' "$file"); do
-          #     role_arn="arn:aws:iam::$account_id:role/GitHubActionsRole"
-          #     stack_name="IamRoleConfigStack-$account_id"
-          #     echo "Deploying stack $stack_name to account $account_id using role $role_arn"
-
-          #   # Debug: Print the role ARN and account ID
-          #   echo "Role ARN: $role_arn"
-          #   echo "Account ID: $account_id"
-
-          #   # Assume the role for the current target account
-          #   assume_target_role $role_arn github-actions
-
-          #   # Deploy the stack
-          #   AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN aws sts get-caller-identity
-          #   AWS_ACCESS_KEY_ID=$TARGET_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$TARGET_AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN=$TARGET_AWS_SESSION_TOKEN cdk deploy $stack_name --require-approval never --context file=$file || { echo "Failed to deploy stack: $stack_name"; exit 1; }
-
-
-          #   # Unset AWS credentials to clear them for the next iteration
-          #   unset TARGET_AWS_ACCESS_KEY_ID
-          #   unset TARGET_AWS_SECRET_ACCESS_KEY
-          #   unset TARGET_AWS_SESSION_TOKEN
-
-          #   # Debug: Confirm credentials are unset
-          #   echo "Unset AWS credentials"
-          #   done
-          # done
-
-        # env:
-        #   IAM_ROLE_CONFIG_DIRECTORY: iamConfigs
-        #   AWS_DEFAULT_REGION: us-east-1  # Set your default region if necessary
-      
-  
